### PR TITLE
Various tweaks

### PR DESCRIPTION
**Pull request by timonson**
This PR is a *WIP* if that's fine with you.

### CODE REVIEW

**Comment by timonson** [comment]
Hi @littledivy ,

I think I am done now.

I believe you forgot to add `arr[0] || arr.shift();` from the [regexparam](https://github.com/lukeed/regexparam/blob/master/src/index.js) library which caused the `"starting slash"` test (which I added) to fail. Please let me know if you removed this line intentionally. I added the line `const arr = str[0] === "/" ? str.slice(1).split("/") : str.split("/")` for readability reasons instead.

Additionally in the `parse` function, I changed the return type from `{ keys: string[] | Boolean; pattern: RegExp }` to `{ keys: string[]; pattern: RegExp }`. The old return type caused some *problems* later on.

The literal empty string type in the union type `Method` is now `"ALL"` instead of `""` like you suggested in your comments.

Last but not least, the handlers can be `async` functions now.

Besides that, I only made some *nit picks*.

In the middleware `pressf-static` I added automatic header setting and parameters and made it async.

Please let me know if you want me to make any improvements.

Thanks!

**Review by littledivy — APPROVED** [review]
LGTM, Thanks for this patch

**Comment by timonson** [comment]
Do you plan to merge this PR @littledivy ?

**Review by littledivy — APPROVED** [review]
This looks perfect! I will merge this, will be nice to benchmark the changes later on.

**Pull request merged**
